import { createTheme } from '@fluentui/react';

export default createTheme({
  palette: {
    themePrimary: '#0078d7',
    themeLighterAlt: '#f3f9fd',
    themeLighter: '#d1e7f8',
    themeLight: '#aad2f3',
    themeTertiary: '#5ca8e7',
    themeSecondary: '#1a84db',
    themeDarkAlt: '#006ac1',
    themeDark: '#005aa3',
    themeDarker: '#004278',
    neutralLighterAlt: '#faf9f8',
    neutralLighter: '#f3f2f1',
    neutralLight: '#edebe9',
    neutralQuaternaryAlt: '#e1dfdd',
    neutralQuaternary: '#d0d0d0',
    neutralTertiaryAlt: '#c8c6c4',
    neutralTertiary: '#a19f9d',
    neutralSecondary: '#605e5c',
    neutralPrimaryAlt: '#3b3a39',
    neutralPrimary: '#323130',
    neutralDark: '#201f1e',
    black: '#000000',
    white: '#ffffff',
    accent: '#ffffff',
  },
  type: 'light',
});
