import { createTheme } from '@fluentui/react';

export default createTheme({
  palette: {
    themePrimary: '#268bd2',
    themeLighterAlt: '#f5fafd',
    themeLighter: '#d7eaf8',
    themeLight: '#b6d9f1',
    themeTertiary: '#74b5e3',
    themeSecondary: '#3c96d7',
    themeDarkAlt: '#227cbc',
    themeDark: '#1d699f',
    themeDarker: '#154d75',
    neutralLighterAlt: '#f6efdd',
    neutralLighter: '#f2ebd9',
    neutralLight: '#e8e2d1',
    neutralQuaternaryAlt: '#d8d2c2',
    neutralQuaternary: '#cec9b9',
    neutralTertiaryAlt: '#c6c1b2',
    neutralTertiary: '#585959',
    neutralSecondary: '#363737',
    neutralPrimaryAlt: '#2e2f2f',
    neutralPrimary: '#000000',
    neutralDark: '#151515',
    black: '#0b0b0b',
    white: '#fdf6e3',
    accent: '#ffffff',
  },
  name: 'warm',
});
