# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AdminTools CD

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci && npm run build --if-present && ls
    # Copying files and artifacts via SSH
    - name: SCP Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST_TEST }}
        username: ${{ secrets.SSH_USERNAME }}
        # key: ${{ secrets.SSH_KEY }}
        password: ${{ secrets.SSH_PASSWORD_TEST }}
        rm: true
        source: "build"
        target: "${{ secrets.SSH_BUILDDIR_TEST }}"
    - name: Debuild nginx
      run: cd .. && docker-compose -f docker-compose-test.yml up --build -d nginx
